---
- name: Add new host
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Add a new host to inventory
      ansible.builtin.add_host:
        name: ansiblehost
        ansible_host: "{{ host_ip }}"
        ansible_user: "{{ ansible_username }}"
- name: Ansible Demo
  hosts: all
  gather_facts: no
  tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 
      
   - name: Install Nginx 
      become: true
      apt:
        name: 
          - nginx 
        state: present
      vars:
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

    - name: Start Nginx service and enable it on boot
      service:
        name: nginx
        state: started
        enabled: yes
